### PR TITLE
Ajax loader

### PR DESCRIPTION
**Pull request by malps13**
This PR is for discussing new ajax loader directive.

### CODE REVIEW

**Comment by malps13** [comment]
@Rush great work!

Can we support also SCSS in directive assets? I've implemented mockup using pure CSS but in my opinion it is always better to use scss, as the resulting code is cleaner and easier to maintenance.

About ajax loader - in my opinion the current design is not working out well, I will simplify it and propose new version, please don't merge it yet.

**Comment by Rush** [comment]
@malps13 Sadly it's hard to do SCSS support in such way. The best we can do is support LESS in this way - would it be ok? Other alternative is to include scss the old fashioned way but it's not as flexible then.

**Comment by malps13** [comment]
@Rush for me LESS is also OK, but on the other hand, using different preprocessors just doesn't seem right as it brings additional diversity in tools that we use.

What if we go with SCSS and make Rails asset pipeline compile it to current location as plain CSS file (webapp/app/javascripts/directives/preloader/preloades.css), wouldn't that work?

**Comment by Rush** [comment]
I agree it is sub-optimal. I know how to implement only half of your idea. :)

**Comment by malps13** [comment]
I am closing it for now, as the ajaxloader and preloader directives are already implemented, and we need  changes from this branch for further development (require css part). However, in the future we need to replace all occurances of old ajax loader gif with new directive, I've added new issue on this (virtkick/virtkick#123).

**Pull request merged**
